cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),





    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

item/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quick_view/', views.quick_view, name='quick_view'),
    path('<item_slug>/', views.item_page, name='item_page'),



    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

stdiplom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.utils import timezone
from pytils.translit import slugify
from PIL import Image
from django.db.models.signals import post_save
import uuid
from random import choices
import string
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.utils.safestring import mark_safe


import os


def format_number(num):
    if num % 1 == 0:
        return int(num)
    else:
        return num

class Category(models.Model):
    subcat = models.ForeignKey('self',blank=True,null=True, on_delete=models.SET_NULL,verbose_name='Относится к категории',related_name='subcats')
    name = models.CharField('Название категории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    page_h1 = models.CharField('Тег H1', max_length=255, blank=True, null=True)
    page_title = models.CharField('Название страницы', max_length=255, blank=True, null=True)
    page_description = models.CharField('Описание страницы', max_length=255, blank=True, null=True)
    page_keywords = models.TextField('Keywords', blank=True, null=True)
    description = RichTextUploadingField('Описание категории', blank=True, null=True)
    old_id = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    isMain = models.BooleanField('Основная категория?', default=True)
    isActive = models.BooleanField('Отображать категорию?', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.name_slug:
            slug = slugify(self.name)
            testSlug = Category.objects.filter(name_slug=slug)
            if testSlug:
                slugRandom = ''
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        if self.isMain:
            return '{} Основная категория : {} '.format(self.old_id,self.name)
        else:
            return '{} Покатегория {} '.format(self.old_id,self.name)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, blank=False, null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    name = models.CharField('Название подкатегории', max_length=255, blank=True, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    page_h1 = models.CharField('Тег H1', max_length=255, blank=True, null=True)
    page_title = models.CharField('Название страницы', max_length=255, blank=True, null=True)
    page_description = models.CharField('Описание страницы', max_length=255, blank=True, null=True)
    page_keywords = models.TextField('Keywords', blank=True, null=True)
    description = RichTextUploadingField('Описание подкатегории', blank=True, null=True)
    views = models.IntegerField(default=0)
    old_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.name_slug:
            slug = slugify(self.name)
            testSlug = SubCategory.objects.filter(name_slug=slug)
            if testSlug:
                slugRandom = ''
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self):
        return 'id :%s , %s ' % (self.id, self.name)

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"



class Item(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='Категория',
                                    on_delete=models.SET_NULL, db_index=True)
    image = models.ImageField('Основное изображение ', upload_to='image', blank=False)
    name = models.CharField('Название ', max_length=255, blank=True, null=True)
    name_lower = models.CharField(max_length=255, blank=True, null=True,default='')
    name_slug = models.CharField(max_length=255, blank=True, null=True,db_index=True)
    price = models.IntegerField('Цена', blank=True, default=0, db_index=True)
    discount = models.IntegerField('Скидка %', blank=True, default=0, db_index=True)
    page_h1 = models.CharField('Тег H1', max_length=255, blank=True, null=True)
    page_title = models.CharField('Название страницы', max_length=255, blank=True, null=True)
    page_description = models.TextField('Описание страницы',  blank=True, null=True)
    page_keywords = models.TextField('Keywords', blank=True, null=True)
    description = RichTextUploadingField('Описание', blank=True, null=True)
    description_main = RichTextUploadingField('Описание краткое', blank=True, null=True)
    description_demo = RichTextUploadingField('Описание для демо', blank=True, null=True)
    chertezh_list = RichTextUploadingField('Информация о проекте', blank=True, null=True)
    comment = models.TextField('Комментарий', blank=True, null=True)
    model = models.CharField('Model', max_length=15, blank=True, null=True)
    sku = models.CharField('SKU', max_length=15, blank=True, null=True)
    file = models.FileField('Файл',  upload_to='files', blank=True, null=True)
    old_id = models.IntegerField(default=0)
    is_active = models.BooleanField('Отображать товар ?', default=True, db_index=True)
    buys = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    order_num = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        self.name_lower = self.name.lower()
        super(Item, self).save(*args, **kwargs)



    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.image.url:
            return mark_safe('<img src="{}" width="100" height="100" />'.format(self.image.url))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    image_tag.short_description = 'Основная картинка'



    @property
    def discount_value(self):
        if self.discount > 0:
            dis_val = self.price - (self.price * self.discount / 100)
        else:
            dis_val = 0
        return (format_number(dis_val))


    def __str__(self):
        return 'id:%s %s' % (self.id, self.name)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"



class ItemImage(models.Model):
    item = models.ForeignKey(Item, blank=False, null=True, on_delete=models.CASCADE, verbose_name='Товар')
    image = models.ImageField('Изображение', upload_to='image', blank=False)
    image_descr = models.TextField('Описание',  blank=True, null=True)
    old_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s Изображение для товара : %s ' % (self.id, self.item.name)

    class Meta:
        verbose_name = "Изображение для товара"
        verbose_name_plural = "Изображения для товара"

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.image:
            return mark_safe('<img src="{}" width="150" height="150" />'.format(self.image.url))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    image_tag.short_description = 'Картинка'





class PromoCode(models.Model):
    promo_code = models.CharField('Промокод (для создания рандомного значения оставить пустым)', max_length=255, blank=True, null=True)
    promo_discount = models.IntegerField('Скидка на заказ', blank=False, default=0)
    use_counts = models.IntegerField('Кол-во использований', blank=True, default=1)
    is_unlimited = models.BooleanField('Неограниченное кол-во использований', default=False)
    is_active = models.BooleanField('Активен?', default=True)
    expiry = models.DateTimeField('Срок действия безлимитного кода', blank=True, null=True)

    def __str__(self):
        if self.is_unlimited:
            return 'Неограниченный промокод со скидкой : %s . Срок действия до : %s' % (self.promo_discount, self.expiry)
        else:
            return 'Ограниченный промокод со скидкой : %s . Оставшееся кол-во использований : %s' % (self.promo_discount, self.use_counts)

    class Meta:
        verbose_name = "Промокод"
        verbose_name_plural = "Промокоды"

    def save(self, *args, **kwargs):
        if self.is_unlimited:
            if not self.promo_code:
                self.promo_code = "LM-"+''.join(choices(string.ascii_uppercase + string.digits, k=5))
                self.use_counts = 0
        else:
            if not self.promo_code:
                self.promo_code = "LM-" + ''.join(choices(string.ascii_uppercase + string.digits, k=5))


        super(PromoCode, self).save(*args, **kwargs)

item/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from item.models import Item,ItemImage
from cart.models import Cart
from customuser.models import User, Guest

def quick_view(request):
    return_dict = {}
    data = request.POST

    item_id = int(data.get('item_id'))
    item = Item.objects.get(id=item_id)
    images = ItemImage.objects.filter(item_id=item_id)
    if item.discount > 0:
        return_dict['item_price_discount'] = item.discount_value
    return_dict['item_id'] = item.id
    return_dict['item_name'] = item.name
    return_dict['item_name_slug'] = item.name_slug
    return_dict['item_description'] = item.description
    return_dict['item_price'] = item.price
    return_dict['item_discount'] = item.discount
    return_dict['item_new'] = item.is_new
    return_dict['item_article'] = item.article
    return_dict['item_present'] = item.is_present
    return_dict['item_images'] = list()
    for image in images:
        return_dict['item_images'].append(image.image_small)
    return JsonResponse(return_dict)




def item_page(request, item_slug):

    try:
        item = Item.objects.get(name_slug=item_slug)
        item.views += 1
        item.save(force_update=True)
        recomended = Item.objects.filter(subcategory_id=item.subcategory_id).order_by('-views')[:12]
        # title = item.name
        # description = item.description


    except:
        raise Http404
        # return render(request, '404.html', locals())
    title = '{} | артикул {} - купить оптом в Москве'.format(item.name, item.article)
    description = 'Заказывайте оптом {} (артикул {}) в интернет-магазине ЛАКШМИ.' \
                  ' Большой выбор товаров на различную тематику по доступным ценам. Доставка по России.'.format(item.name, item.article)
    return render(request, 'item/item.html', locals())

templates/page/checkout.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
    <div id="content">    <div class="breadcrumb">
        <a href="/">Главная</a>
        » <a href="#">Оформление заказа</a>
    </div>
        <h1>Оформление заказа</h1>
        <div class="simple-content">
            <div class="simplecheckout" id="simplecheckout_form">
                <!-- simplecheckout form -->
                <div class="simplecheckout-block" id="simplecheckout_cart">
                    <table class="simplecheckout-cart">
                        <thead>
                        <tr>
                            <th class="image">Фото</th>
                            <th class="name">Наименование товара</th>
                            <th class="model">Модель</th>
                            <th class="quantity"><span title="Количество">Кол-во</span></th>
                            <th class="price">Цена</th>
                            <th class="total">Итого</th>
                            <th class="remove"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cart_item in all_items_in_cart %}
                            <tr>
                                <td class="image">
                                    <a href="#">
                                        <img style="width: 150px" src="{{ cart_item.item.image.url }}" alt="{{ cart_item.item.name }}" title="{{ cart_item.item.name }}"></a>
                                </td>
                                <td class="name">
                                    <div class="image">
                                        <a href="#">
                                            <img src="{{ cart_item.item.image.url }}" alt="{{ cart_item.item.name }}" title="{{ cart_item.item.name }}"></a>
                                    </div>
                                    <a href="#">{{ cart_item.item.name }}</a>
                                    <div class="options">
                                    </div>
                                </td>
                                <td class="model">{{ cart_item.item.sku }}</td>
                                <td class="quantity">
                                    {{ cart_item.number }}
                                </td>
                                <td class="price"><nobr>{{ cart_item.item.price }} р.</nobr></td>
                                <td class="total"><nobr>{{ cart_item.total_price }} р.</nobr></td>
                                <td class="remove">
                                <td class="remove"><a href="{% url 'del4cart' cart_item.item.id %}">X</a></td></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>


                    <div class="simplecheckout-cart-total" id="total_total">
                        <span><b>Итого:</b></span>
                        <span class="simplecheckout-cart-total-value"><nobr>{{ total_cart_price }} р.</nobr></span>

                    </div>

                    <input type="hidden" name="remove" value="" id="simplecheckout_remove">

                </div><div class="simplecheckout-block" id="simplecheckout_customer"><div class="simplecheckout-block-heading">
                Покупатель    </div>
                <div class="simplecheckout-block-content">
                    <input type="hidden" name="checkout_customer[address_id]" id="customer_address_id" value="0">
                    <div class="simplecheckout-customer-block">
                        <form action="{% url 'checkout' %}" method="post">{% csrf_token %}
                                   <table class="simplecheckout-customer-two-column-left">
                            <tbody><tr>
                                <td class="simplecheckout-customer-left">
                                    <span class="simplecheckout-required">*</span>
                                    E-mail                            </td>
                                <td class="simplecheckout-customer-right">
                                    <input type="text" class="simplecheckout-red-border" id="checkout_customer_main_email" name="email" value="">                                                            </td>
                            </tr>
                            <tr class="simple_table_row ">
                                <td class="simplecheckout-customer-left">
                                    <span class="simplecheckout-required">*</span>
                                    Имя                        </td>
                                <td class="simplecheckout-customer-right">
                                    <input type="text" class="simplecheckout-red-border" id="checkout_customer_main_firstname" name="fio" value="">                                                    </td>
                            </tr>
                            </tbody></table>
                        <table class="simplecheckout-customer-two-column-right">
                            <tbody><tr class="simple_table_row ">
                                <td class="simplecheckout-customer-left">
                                    <span class="simplecheckout-required">*</span>
                                    Телефон                        </td>
                                <td class="simplecheckout-customer-right">
                                    <input type="text" class="simplecheckout-red-border" id="checkout_customer_main_telephone" name="phone" value="">                                                    </td>
                            </tr>
                            <tr class="simple_table_row ">
                                <td class="simplecheckout-customer-left">
                                    Комментарий                        </td>
                                <td class="simplecheckout-customer-right">
                                    <textarea type="text" id="checkout_customer_main_comment" name="comment"></textarea>                                                    </td>
                            </tr>
                            </tbody></table>

                                <button class="button btn" type="submit">Оформить заказ</button>

                        </form>
               </div>

                <div class="simplecheckout-payment-text">Во избежание продажи одного и того же диплома в один ВУЗ, просьба указать в комментарии учебное заведение (с расшифровкой), факультет, кафедру, форму обучения (дневная, вечерняя, заочная). Вся информация, разумеется, останется строго конфиденциальной.</div></div>    <input type="hidden" name="simple_create_order" id="simple_create_order" value="">



            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/page/item.html
{% extends 'basic.html' %}

{% block content %}

    <div id="notification"></div>
   {% include 'page/side_menu.html' %}

    <div id="content">  <div class="breadcrumb">
        <a href="/">Главная</a>
        &raquo; <a href="{% url 'category' item.category.name_slug %}">{{ item.category.name }}</a>
        &raquo; <a href="#">{{ item.name }}</a>
    </div>
        <h1>{{ item.page_h1 }}</h1>
        <div  class="product-info">
            <div class="left">
                <div class="image"><a href="{{ item.image.url }}" title="{{ item.name }}" class="colorbox" rel="colorbox"><img style="width: 300px" src="{{ item.image.url }}" title="{{ item.name }}" alt="{{ item.name }}" id="image" /></a>
                    <div style="max-width:468px;">14-ти этажный жилой дом с подземной автостоянкой в г. Белгород</div>
                </div>
                <div style="display: flex; flex-wrap: wrap" class="image-additional">
                    {% for image in item.itemimage_set.all %}

                        <div class="htooltip">
                            <a href="{{ image.image.url }}" title="{{ image.image_descr }}" class="colorbox" rel="colorbox" style="text-decoration:none;"><img style="width: 75px" src="{{ image.image.url }}" title="{{ image.image_descr }}" alt="{{ image.image_descr }}" />
                                <span>{{ image.image_descr }}</span>
                            </a></div>
                    {% endfor %}
                </div>

                <div class="videoproduct"></div>

            </div>
            <div class="right">
                <div class="description">

                    <div class="description-main">
                        {{ item.description_main | safe }}
                 </div>

                </div>
                <div class="price">Цена:{{ item.price }} р.                <br />
                </div>





                <div class="cart">
                    <div>
                        <a href="{{ item.file.url }}" id="button-cart" class="button2">Скачать демо</a>
                        <a href="{% url 'add2cart' item.id %}" id="button-cart" class="button2">Купить</a>





                        <!--noindex--><div style="clear:right; padding-top:12px;"><p>
                            Скачайте DEMO-версию дипломного проекта и утвердите в своем вузе. В DEMO-версию входят чертежи (фасад, план и разрез), а также конструктивное и объемно-планировочное решение объекта. Все, что необходимо для утверждения темы проекта!</p>
                        </div><!--/noindex-->
                    </div>
                </div>

                <h3>Похожие проекты:</h3>
                <div id="tab-related">
                    <div class="box-product2">
                        {% for item in simlar %}
                        <div class="product">
                            <div class="image">
                                <a href="{% url 'item' item.category.name_slug item.name_slug %}">
                                    <img style="width: 80px" src="{{ item.image.url }}" alt="{{ item.name }}" />
                                </a>
                            </div>
                            <div class="name">
                                <a href="{% url 'item' item.category.name_slug item.name_slug %}">{{ item.name }}</a>
                            </div>
                            <!--                <div class="price">
                                                4 000 р.                  </div>
                                    -->                <!--<a onclick="addToCart('79');" class="button">Купить</a>-->
                        </div>
                        {% endfor %}

                    </div>
                </div>


            </div>
        </div>

        <div id="tabs" class="htabs"><a href="#tab-description">Содержание</a>
            <a href="#tab-chertezh">Информация о проекте</a>
        </div>

        <div id="tab-description" class="tab-content">
            {{ item.description |safe }}
        </div>
        <div id="tab-chertezh" class="tab-content">
            {{ item.chertezh_list |safe }}
        </div>


        <div class="box">
            <div class="box-heading">Другие дипломы этой категории</div>
            <div class="box-content">
                <div class="box-product">
                    {% for item in other %}
                    <div>
                        <div class="image">
                            <a href="{% url 'item' item.category.name_slug item.name_slug %}">
                                <img style="width: 90px" src="{{ item.image.url }}" alt="{{ item.name }}" />
                            </a></div>
                        <div class="name"><a href="{% url 'item' item.category.name_slug item.name_slug %}">{{ item.name }}</a>
                        </div>
                        <div class="price">
                            {{ item.price }} р.			  			</div>
                        <div class="cart">
                             <a href="{% url 'add2cart' item.id %}" class="button">В корзину</a>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript"><!--
    if(window.innerWidth <= 1024) {
        $('.colorbox').colorbox({
            current: '',
            title: '',
            overlayClose: true,
            opacity: 0.5,
            width: '100%'
        });
    } else {
        $('.colorbox').colorbox({
            current: '',
            title: '',
            overlayClose: true,
            opacity: 0.5,
        });
    }
    $("#colorbox").on("swiperight", function ( event ){
        $.colorbox.prev();
    });
    $("#colorbox").on("swipeleft", function ( event ){
        $.colorbox.next();
    });
    //--></script>
    <script type="text/javascript"><!--
    $('#button-cart').bind('click', function() {
        $.ajax({
            url: 'index.php?route=checkout/cart/add',
            type: 'post',
            data: $('.product-info input[type=\'text\'], .product-info input[type=\'hidden\'], .product-info input[type=\'radio\']:checked, .product-info input[type=\'checkbox\']:checked, .product-info select, .product-info textarea'),
            dataType: 'json',
            success: function(json) {
                $('.success, .warning, .attention, information, .error').remove();

                if (json['error']) {
                    if (json['error']['option']) {
                        for (i in json['error']['option']) {
                            $('#option-' + i).after('<span class="error">' + json['error']['option'][i] + '</span>');
                        }
                    }
                }

                if (json['success']) {
                    $('#notification').html('<div class="success" style="display: none;">' + json['success'] + '<img src="catalog/view/theme/default/image/close.png" alt="" class="close" /></div>');

                    $('.success').fadeIn('slow');

                    $('#cart-total').html(json['total']);

                    window.location.href = '../index47cc.html?route=checkout/simplecheckout';  // Added by Best-Byte //
                }
            }
        });
    });
    //--></script>
    <script type="text/javascript"><!--
    $('#review .pagination a').live('click', function() {
        $('#review').fadeOut('slow');

        $('#review').load(this.href);

        $('#review').fadeIn('slow');

        return false;
    });

    $('#review').load('../index8ce7.html?route=product/product/review&amp;product_id=72');

    $('#button-review').bind('click', function() {
        $.ajax({
            url: 'index.php?route=product/product/write&product_id=72',
            type: 'post',
            dataType: 'json',
            data: 'name=' + encodeURIComponent($('input[name=\'name\']').val()) + '&text=' + encodeURIComponent($('textarea[name=\'text\']').val()) + '&rating=' + encodeURIComponent($('input[name=\'rating\']:checked').val() ? $('input[name=\'rating\']:checked').val() : '') + '&captcha=' + encodeURIComponent($('input[name=\'captcha\']').val()),
            beforeSend: function() {
                $('.success, .warning').remove();
                $('#button-review').attr('disabled', true);
                $('#review-title').after('<div class="attention"><img src="catalog/view/theme/default/image/loading.gif" alt="" /> Пожалуйста, подождите!</div>');
            },
            complete: function() {
                $('#button-review').attr('disabled', false);
                $('.attention').remove();
            },
            success: function(data) {
                if (data['error']) {
                    $('#review-title').after('<div class="warning">' + data['error'] + '</div>');
                }

                if (data['success']) {
                    $('#review-title').after('<div class="success">' + data['success'] + '</div>');

                    $('input[name=\'name\']').val('');
                    $('textarea[name=\'text\']').val('');
                    $('input[name=\'rating\']:checked').attr('checked', '');
                    $('input[name=\'captcha\']').val('');
                }
            }
        });
    });
    //--></script>
    <script type="text/javascript"><!--
    $('#tabs a').tabs();
    //--></script>
    <script type="text/javascript" src="../catalog/view/javascript/jquery/ui/jquery-ui-timepicker-addon.js"></script>
    <script type="text/javascript"><!--
    if ($.browser.msie && $.browser.version == 6) {
        $('.date, .datetime, .time').bgIframe();
    }

    $('.date').datepicker({dateFormat: 'yy-mm-dd'});
    $('.datetime').datetimepicker({
        dateFormat: 'yy-mm-dd',
        timeFormat: 'h:m'
    });
    $('.time').timepicker({timeFormat: 'h:m'});
    //--></script>


{% endblock %}

templates/page/item_card.html
<div style="display: flex;padding: 10px 0; flex-wrap: wrap; justify-content: space-between">

         <div  class="image">
        <a href="{% url 'item' item.category.name_slug item.name_slug %}">
            <img style="width: 200px" src="{{ item.image.url }}" title="{{ item.name }}" alt="{{ item.name }}" />
        </a>
    </div>


   <div style="flex-basis: 55%">
       <div class="name">
        <a href="{% url 'item' item.category.name_slug item.name_slug %}">{{ item.name }}</a>
    </div>
      <div class="description">

     {{ item.description_main  |safe | escape }}
    </div>

   </div>
    <div style="display: flex; flex-direction: column; justify-content: space-between">
          <div class="price">
        {{ item.price }} р.
    </div>

         <div class="cart">

        <a href="{% url 'item' item.category.name_slug item.name_slug %}" class="button-big">Подробнее</a>
    </div>
    </div>






</div>